---
title: "For Organizers"
author: "Hackathon Committee"
date: "2024-02-08"
categories: [news]
toc: true
---

Law students, programmers, data scientists, and other eager advocates and community members will spend a weekend designing solutions to social justice problems and challenges. Examples of projects include: 

* Building a data dashboard to show where in Philly is the greatest need for your services
* Building a website to help the public connect to the services you provide
* Building a chatbot for the public to access information about their legal rights.

## Let us know what we can build for you!

You have experience with pressing social justice challenges in Philadelphia. We need your insights to mobilize these teams in the right direction.

Would you be willing to provide a brief description of potential projects and let us know if you are available to meet with us to review them?

We invite you to

* Share your expertise with participants
* Provide challenges participants can design and develop solutions for at the hackathon
* Work with the hackathon committee to develop long-term collaborations.

Our event will bring together as many as 150 volunteers with a wide range of expertise, including coding, law, and policy. Participants will divide into teams and spend two intense days building tailored solutions to the challenges you've presented. 

## Contact us! 

We'd love to hear from you about solutions you'd like Philly’s social justice innovators to design.

* Reach out to us at info@socialjusticehackathon.com if you have ideas for projects for hackathon teams
* [Fill out this form](https://docs.google.com/forms/d/1CaHIVtf3pohPl34DduosxeKB87p8WAfZ0cMbEgosCG0) to schedule a meeting with us to discuss how our hackathon can help you and the Philadelphia community.